apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis-pv.yaml
- redis-pvc.yaml
- redis-master-depl.yaml
- redis-master-service.yaml
- notebook-service.yaml
- notebook-depl.yaml
- ingress.yaml
images:
- name: 381492301125.dkr.ecr.us-east-1.amazonaws.com/notebook
  newName: 381492301125.dkr.ecr.us-east-1.amazonaws.com/notebook
  newTag: 5120de
